blank_issues_enabled: false

contact_links:
  - name: "🤔 Got a question?"
    url: https://github.com/acheemala/threat-hunter/discussions/new?category=stuck
    about: Post in Discussions before opening an issue.

  - name: "💡 Got an idea?"
    url: https://github.com/acheemala/threat-hunter/discussions/new?category=ideas
    about: Share feature ideas in Discussions before opening an issue.
